# Generated by Django 3.2.3 on 2021-05-31 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0002_alter_student_year_of_graduation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_of_graduation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
